### ISSUE TITLE
5.0.0: Connection problems to FIPs using neutron_ovn_distributed_fip=true with ovn 22.09 and ovs 3.0.1 

### ISSUE THREAD

**Issue by nerdicbynature** [osism/issues#490]
Hi,

today we discovered a serious problem (actually showstopper for R4) with ovn and ovs using versions mentioned above and having enabled ovn feature neutron_ovn_distributed_fip=true. The latter helped us solving several performance issues, so disabling is a very bad option.

Problem description:
When trying to connect (e.g. connect to port 22 or port 80) from a fip-less instance to an another instance's fip in the same project, the connection fails. In tcpdump we see on the target instance that the source address of the source instance has not been source-natted by the outgoing gateway. As for this the return packet is sent directly to the first instance which does not know about this connection.

Reproduce:
Start three instances a (with fip), b (without fip), c (with fip)
ssh to "a" via fip, from there ssh to instance "b"
from "b" try to connect to ssh to fip of instance "c" -> should work

Enable neutron_ovn_distributed_fip=true
Reconfigure ovn and neutron
Try again to connect from "b" to fip of "c" -> timeout

We also tried: restarting ovn (and subcomponents), ovs, neutron.

If you set neutron_ovn_distributed_fip=false it works again

Kind regards,
André.

Update: changed enable-chassis-as-gw to neutron_ovn_distributed_fip. Seems I mixed up both params

**Comment by berendt** [comment]
in environments/kolla/images.yml the following entry should be sufficient for newer Zed OVN images. Can you please test?

```
kolla_ovn_version: "zed"
```

**Comment by maliblatt** [comment]
> `kolla_ovn_version: "zed"`

rollout works in test environment with expected version. next step is, we will bring it to our dev environment and investigate if the problem still exists. We keep the issue updated as soon as we have new findings.
thanks @berendt

**Comment by maliblatt** [comment]
One more thing, the OVN components seems to be linked with OVS 3.1.0:

```
ovn-controller 23.03.0
Open vSwitch Library 3.1.0
```

but in the daily build openvswitch containers I see:
`ovs-vswitchd (Open vSwitch) 3.0.1`

Would it make sense to also upgrade openvswitch containers to 3.1.0 ?

**Comment by maliblatt** [comment]
it looks like that OVN 23.03.0 makes us very happy, after rolling it out to our dev env the problem with reaching fips on same router has gone!

We will do some further tests and put it to our stage env but I am very confident that we can resume the updates on the productive environments very soon.

@berendt could you provide a tagged container image for the 23.03.0 ovn components on quay.io? we would like to make sure the versions we are testing now are the same, that we will bring to production later :-)
Thanks!!
Markus

**Comment by fkr** [comment]
@maliblatt thanks for your tests. That is very helpful!

**Comment by berendt** [comment]
We are also still testing on our environment and then I make a 5.1.0 quite quickly.

**Comment by maliblatt** [comment]
OVN 23.03.0 on gx-scs / scs1 works also fine and as expected.
Only on our staging environment we hat to do some reconfigures with fip-routing off and turning it on again to get it working without the initial issue.
But up to now it seems the new versions works properly.

**Comment by garloff** [comment]
Good news, thanks for the update!

**Comment by berendt** [comment]
Should we still go up from OVS 3.0.1 to OVS 3.1.0 before 5.1.0 or just OVN with 23.03 for now and OVS later?

**Comment by nerdicbynature** [comment]
We would like to have 3.1 if possible.

We have already left the LTS track with 3.0.1 and in my opinion it does not make sense to stick on an older release "in between".

Regarding to OVS's faq (https://docs.openvswitch.org/en/latest/faq/releases/) they relase new versions twice a year. That would be a good fit with SCS' release cycles.

What's more: Bugs get fixed in the latest release and in the LTS release, and *may* be fixed in older version. So if we stay at 3.0.1 it's not clear whether there will be a bugfix at all.

We should also consider always having the latest OVS and also OVN release in SCS releases. See also https://docs.ovn.org/en/latest/internals/release-process.html

As for this, we like to switch to OVS 3.1.

**Comment by fkr** [comment]
I'd second what @nerdicbynature said.

**Comment by maliblatt** [comment]
we used the daily openvswitch build with the 'zed' tag to upgrade the OVS on our dev/stage and on scs1 (gx-scs) to OVS 3.1.0.
Our first impression is very positive. We will monitor the environments over the weekend and will see if everything stays that good.

**Comment by matofeder** [comment]
> ... to upgrade the OVS on our dev/stage and on scs1 (gx-scs) to OVS 3.1.0. Our first impression is very positive ...

Does it mean that upgrade on **prod** scs1 (gx-scs) stage will come soon? I suppose that  dev/stage you mentioned is different from the productive one where e.g. "p500924-dnation" and other projects live (because we are still facing the issue with FIP e.g. in the mentioned  p500924 project).

**Comment by matofeder** [comment]
> scs1 / gx-scs has already been updated last friday. In our test projects we can not see the bug anymore, so can you please tell me, from which instance (source-ip) you are trying to reach which destination fip ? I will take a look into it.

My current test deployment in  p500924-dnation project consist of:

- test_vm_0 with FIP: 213.131.230.161
- test_vm_1 with FIP: 213.131.230.243
- test_vm_2 without FIP

I can ping test_vm_0's FIP: 213.131.230.161 from test_vm_1, but not from test_vm_2

**Comment by osfrickler** [comment]
Please try to continue the debugging session outside of this issue, feel free to report the result though.

**Comment by garloff** [comment]
> My current test deployment in  p500924-dnation project consists of:
> 
> - test_vm_0 (10.1.0.111) with FIP: 213.131.230.161
> - test_vm_1 (10.1.0.143) with FIP: 213.131.230.243
> - test_vm_2 (10.1.0.163) without FIP
> 
> I can ping test_vm_0's FIP: 213.131.230.161 from test_vm_1, but not from test_vm_2.  So the VM with source IP 10.1.0.163 is unable to reach the VM with public IP 213.131.230.161

You could tcpdump on the receiving test_vm_0. I guess the SNAT does not happen for the outgoing traffic. The ping response thus goes directly to 10.1.0.163 which can probably see it (if the Sec Group allows the pong to go through), but not associate response with the ping as it comes from 10.1.0.111 instead of 213.131.230.161.

Just my theory. Please test!

Upgrade of scs1: Does it already have ovm-2023.03/ovs-3.1?
If so, were the VMs created freshly since the upgrade?

**Comment by maliblatt** [comment]
UPDATE:
it seems that we have found the root cause for the problem. from our findings the problem is not located in OVS/OVN itself, but cames from a neutron patch which is included in neutron-server 21.1.1.dev6, which is delivered with the osism neutron container with 21.1.1.20230321 tag.
The patch in neutron has been (partly) reverted around March, 13th and !!luckily!! is included in the latest daily build zed container, which deliveres  21.1.1.dev12!

details can be found here:
https://review.opendev.org/c/openstack/neutron/+/875644

we successfully tested with neutron 21.1.1.dev12 and activated distributed fip routing feature on our dev environment and since some minutes also on gx-scs / scs1

@matofeder can you please verify if everything on gx-scs works as expected for you?

**Comment by matofeder** [comment]
> @matofeder can you please verify if everything on gx-scs works as expected for you?

I can confirm that your fix resolved the issue with my test deployment (i.e.  VM with source IP 10.1.0.163 is **able** to reach the VM with public IP 213.131.230.161). In addition, I spawned 6 more VMs (3cp + 3 worker node k8s cluster) where each node should be joined through FIP  and everything works as expected.

**Comment by berendt** [comment]
Thanks for all the testing and debugging. The 5.1.0 is prepared so far and on the rolling zed tags the problem is also taken care of. i close this and refer to it in the release notes.
